config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "articles#index"
  resources :users
  
  get '/articles/unrated', to: 'articles#unrated'
  get '/articles/yesses',  to: 'articles#yesses'
  get '/articles/numbered', to: 'articles#sorted_by_id'
  
  resources :articles
  resources :differences

  get '/differences/nose', to: 'differences#nose'
  
  resources :reviews do
    post "read"
    post "ignore"
    post "duplicate"
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessor :authors
  
  has_many :reviews
  has_many :users, through: :reviews
  
  def authors
    encd self[:authors]
  end
  
  def abstract
    encd self[:abstract]
  end
  
  def encd(string)
    string = "«Not available»" if string.nil? or string == ""
    string
  end
  
  def for_user(user)
    self.reviews.find_by_user_id(user)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /articles
  # GET /articles.json
  def index
    # @articles = Article.all
    @articles = current_user.articles.order(:title).paginate(page: params[:page], per_page: 30)
  end
  
  def unrated
    @articles = current_user.articles.order(:title).where("result = ''").paginate(page: params[:page], per_page: 30)
    render 'index'
  end
    
  def yesses
    @articles = current_user.articles.order(:id).where("result = 'Y' and user_id = 1").paginate(page: params[:page], per_page: 10)
    render 'index'
  end
  
  def sorted_by_id
    # @articles = Article.all
    @articles = current_user.articles.order(:id).paginate(page: params[:page], per_page: 150)
    render 'index'
  end
  
  # GET /articles/1
  # GET /articles/1.json

  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:origID, :source, :title, :authors, :url, :abstract)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.haml
- @review = article.for_user(current_user)
%tr
  %td= article.id
  %td{id: "review-read-#{@review.id}"}
    = render 'reviews/read_button'
  %td{id: "review-ignore-#{@review.id}"}
    = render 'reviews/ignore_button'
  %td{id: "review-duplicate-#{@review.id}"}
    = render 'reviews/duplicate_button'
  %td= article.source
  %td
    = link_to article.title, article.url, {title: "Abstract", :target => "_blank", data: {trigger:"hover", container: "body", toggle: "popover", placement: "right", content: "#{article.abstract}", html: true}}
  %td= article.authors

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :origID %><br>
    <%= f.number_field :origID %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :authors %><br>
    <%= f.text_field :authors %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :abstract %><br>
    <%= f.text_area :abstract %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.haml
%p#notice= notice

%h1 Listing Articles for #{current_user.name}

.apple_pagination
  .page_info
    = page_entries_info @articles
  = will_paginate @articles, :container => false

%table.table.table-condensed
  %thead
    %tr
      %th.col-md-2{colspan: 4}
      %th.col-md-10{colspan: 3}
    %tr
      %th id
      %th.center{colspan: "3"} Include?
      %th Source
      %th Title
      %th Authors
      
  %tbody
    = render @articles

.apple_pagination
  = will_paginate @articles

:javascript
  $(function () { 
    $("[data-toggle='popover']").popover();
  });

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/results.html.haml
%p#notice= notice

%h1 Listing Current Status for All Articles

.apple_pagination
  .page_info
    = page_entries_info @articles
  = will_paginate @articles, :container => false

%table.table.table-condensed
  %thead
    %tr
      %th.col-md-2{colspan: 4}
      %th.col-md-10{colspan: 3}
    %tr
      %th id
      %th.center{colspan: "3"} Include?
      %th Source
      %th Title
      %th Authors
      
  %tbody
    - for article in @articles
      %tr
        %td= article.id
        %td
          = render 'reviews/read_icon'
        %td
          = render 'reviews/ignore_icon'
        %td
          = render 'reviews/duplicate_icon'
        %td= article.source
        %td
          = link_to article.title, article.url, {title: "Abstract", :target => "_blank", data: {trigger:"hover", container: "body", toggle: "popover", placement: "right", content: "#{article.abstract}", html: true}}
        %td= article.authors
.apple_pagination
  = will_paginate @articles

:javascript
  $(function () { 
    $("[data-toggle='popover']").popover();
  });

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Origid:</strong>
  <%= @article.origID %>
</p>

<p>
  <strong>Source:</strong>
  <%= @article.source %>
</p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Authors:</strong>
  <%= @article.authors %>
</p>

<p>
  <strong>Url:</strong>
  <%= @article.url %>
</p>

<p>
  <strong>Abstract:</strong>
  <%= @article.abstract %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>