config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "articles#index"
  resources :users
  
  get '/articles/unrated', to: 'articles#unrated'
  get '/articles/yesses',  to: 'articles#yesses'
  get '/articles/numbered', to: 'articles#sorted_by_id'
  
  resources :articles
  resources :differences

  get '/differences/nose', to: 'differences#nose'
  
  resources :reviews do
    post "read"
    post "ignore"
    post "duplicate"
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
#   before_action :set_review, only: [:read, :ignore]
  before_action :set_review_by_review_id, only: [:read, :ignore, :duplicate]
  before_action :authenticate_user!
  
  def show
  end
    
  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def read
    if @review.result == "Y"
      @review.result = ""
    else
      @review.result = "Y"
    end
    save_and_update_buttons
  end

  def ignore
    if @review.result == "N"
      @review.result = ""
    else
      @review.result = "N"
    end
    save_and_update_buttons
  end
  
  def duplicate
    if @review.result[0] == "D"
      @review.result = ""
    else

      @review.result = "D#{params[dup_to_sym]}"
    end
    save_and_update_buttons
  end

  private
  
    def save_and_update_buttons
      @article = @review.article
      respond_to do |format|
        if @review.save
          format.html { redirect_to @review, notice: 'Review was successfully updated.' }
          format.js { render 'update_buttons', layout: false }
          format.json { render :show, status: :ok, location: @review }
        else
          format.html { render :edit }
          format.json { render json: @review.errors, status: :unprocessable_entity }
        end
      end
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end
    
    def set_review_by_review_id
      @review = Review.find(params[:review_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:result, dupToSym)
    end
    
    def dup_to_sym
      "text-duplicate-#{@review.id}".to_sym
    end
end

app/views/reviews/_duplicate_button.html.haml
- if @review.result[0] == "D"
  - btn_class = "btn btn-info"
  - dupval = @review.result[1,@review.result.length]
- else
  - btn_class = "btn btn-inverse"
  - dupval = nil
= form_tag review_duplicate_path(@review), remote: true do
  .input-group
    %span.input-group-btn
      = button_tag :class=>btn_class do
        %span.glyphicon.glyphicon-duplicate
    = text_field_tag "text-duplicate-#{@review.id}".to_sym, dupval, class: "form-control smaller-font", placeholder: "#"

app/views/reviews/_ignore_button.html.haml
- if @review.result == "N"
  - btn_class = "btn btn-danger"
- else
  - btn_class = "btn btn-inverse"
= button_to review_ignore_path(@review), :class=>btn_class, :remote=>true do
  %span.glyphicon.glyphicon-remove
  

app/views/reviews/_read_button.html.haml
- if @review.result == "Y"
  - btn_class = "btn btn-success"
- else
  - btn_class = "btn btn-inverse"
= button_to review_read_path(@review), :class=>btn_class, :remote=>true do
  %span.glyphicon.glyphicon-ok

app/views/reviews/update_buttons.js.erb
$('#review-read-<%= @review.id %>').html("<%= escape_javascript(render 'read_button') %>");
$('#review-ignore-<%= @review.id %>').html("<%= escape_javascript(render 'ignore_button') %>");
$('#review-duplicate-<%= @review.id %>').html("<%= escape_javascript(render 'duplicate_button') %>");
$('#progress').html("<%= escape_javascript(render 'layouts/progress') %>");