config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "articles#index"
  resources :users
  
  get '/articles/unrated', to: 'articles#unrated'
  get '/articles/yesses',  to: 'articles#yesses'
  get '/articles/numbered', to: 'articles#sorted_by_id'
  
  resources :articles
  resources :differences

  get '/differences/nose', to: 'differences#nose'
  
  resources :reviews do
    post "read"
    post "ignore"
    post "duplicate"
  end
end

app/views/layouts/_messages.html.haml
-# app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    - case name
    - when "notice"
      - type = "success"
    - when "info"
      - type = "info"
    - when "warning"
      - type = "warning"
    - when "error"
      - type = "danger"
    - when "alert"
      - type = "danger"
    - else type = name
    %div{:class => "alert alert-#{type}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} LitRes
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li.active
          %a{:href => "/"} Home
        -if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Articles
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to('Alphabetically', articles_path)
              %li
                = link_to('By ID', articles_numbered_path)
              %li
                = link_to('Selected articles', articles_yesses_path)
              %li
                = link_to('Unrated articles', articles_unrated_path)
      %ul.nav.navbar-nav.navbar-right
        -if user_signed_in?
          = render 'devise/menu/signed_in'
        - else
          = render 'devise/menu/login'
      %ul.nav.navbar-nav.navbar-right#progress
        = render 'layouts/progress'
          

app/views/layouts/_progress.html.haml
%li 
  %a{href: "#"}
    Read: 
    %span.read-articles= "#{Review.read(current_user)}" 
    Ignore: 
    %span.ignored-articles= "#{Review.ignore(current_user)}" 
    Duplicate: 
    %span.duplicate-articles= "#{Review.duplicates(current_user)}"
    To be done: 
    %span.to-be-done-articles= "#{Review.to_be_done(current_user)}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale = 1"}
    %title= content_for?(:title) ? yield(:title) : envir + ": Literature Research"
    %meta{:content => content_for?(:description) ? yield(:description) : "App_Name", :name => "description"}
    = stylesheet_link_tag :application, :media => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag :application, 'data-turbolinks-track' => true
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top 
      -#.navbar-inverse
      -# %nav.navbar-inner
      = render 'layouts/navbar'
      -#
        %nav.navbar.navbar-default
          -# .container
          .container-fluid
            .navbar-header
        
            = # render 'devise/menu/registration_items'
            = # render 'devise/menu/login_items'
          
      -# %a.brand{:href => "/"} LitRes
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = yield
          %footer